title: Rogério Lopes # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
plugins:
  - jemoji
description: > # text below
  <h4> Data Science <br>
  <img style="vertical-align:middle" src="https://cdn3.iconfinder.com/data/icons/google-material-design-icons/48/ic_location_on_48px-1024.png" height="20" width="20" class="center"/> Brasil/São Paulo</h4>
  
  <p>Construo ferramentas analíticas para entender problemas críticos com suporte de insights quantitativos.</p><br>
  <br>
  <a href="mailto:rogerio_288@hotmail.com"><img style="vertical-align:middle" src="https://cdn-icons-png.flaticon.com/128/11893/11893321.png" height="23" width="23" class="center"/> E-mail</a><br>
  <a href="https://github.com/RogerioLS"><img style="vertical-align:middle" src="https://cdn.iconscout.com/icon/free/png-256/github-113-438180.png" height="22" width="22" class="center"/> Github</a><br> 
  <a href="https://www.linkedin.com/in/rogerio-lopes-57627615b/"><img style="vertical-align:middle" src="https://cdn-icons-png.flaticon.com/512/174/174857.png" height="20" width="20" class="center"/> LinkedIn</a><br> 

  </p>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
